### PR TITLE
Updated GUI to the UI concept design

### PR DESCRIPTION
**Pull request by gachia**
add: Used Icons from docs to create 32x32 pixels icons for Application usage in resources folder
chore: Updated App Icon with product icon and added Icon to menu bar
chore: Moved UI elements to follow UI design
chore: Added Send button for mouse click
chore: Added Title labels for main Appointment and Patient addressbook

### CODE REVIEW

**Comment by gachia** [comment]
image
This is what the application looks like now

**Comment by gachia** [comment]
> Is visitWindowIcon.png slightly squished horizontally? Did you scale it with fixed aspect ratio? Might just be my eyes, but I believe the aspect ratio wasn't preserved when you scaled it down.

Yes it is squished. Aspect Ratio wasn't preserved, cropped to 32 x 32pixels.

**Comment by Q-gabe** [comment]
> > Is visitWindowIcon.png slightly squished horizontally? Did you scale it with fixed aspect ratio? Might just be my eyes, but I believe the aspect ratio wasn't preserved when you scaled it down.
> 
> Yes it is squished. Aspect Ratio wasn't preserved, cropped to 32 x 32pixels.

Could you fix that haha, it's relatively minor but I think it's important to maintain a certain aesthetic integrity throughout. I could help with that of course, post-merge. Would you like me to help?

**Comment by gachia** [comment]
> > > Is visitWindowIcon.png slightly squished horizontally? Did you scale it with fixed aspect ratio? Might just be my eyes, but I believe the aspect ratio wasn't preserved when you scaled it down.
> > 
> > 
> > Yes it is squished. Aspect Ratio wasn't preserved, cropped to 32 x 32pixels.
> 
> Could you fix that haha, it's relatively minor but I think it's important to maintain a certain aesthetic integrity throughout. I could help with that of course, post-merge. Would you like me to help?

You might need to upload a new image if you want to keep Aspect Ratio. Default isn't square aspect ratio (or what the proper term is called)

**Comment by Q-gabe** [comment]
> You might need to upload a new image if you want to keep Aspect Ratio. Default isn't square aspect ratio (or what the proper term is called)

Ah, I see the issue. I will send you the edited file via Tele.

**Pull request merged**
