### PR TITLE
docs: update UG to reflect changes in v1.2

### PR DESCRIPTION
**Pull request by Q-gabe**
The User Guide has been updated to reflect all the new features / changes we have done going from v1.1 to v1.2.

Preview the new UG [here](https://github.com/Q-gabe/main/blob/update-UGDG/docs/UserGuide.adoc).

**Stuff changed:**
* TIP, WARNING, NOTE captions now available per command so users can get a better idea of how to use the commands.
* Updated all the old commands in UG to reflect the new commands everyone implemented in v1.2.
* Enhanced hierarchy of commands so that its not so messy looking.

Please review the commands for your components and see if anything needs changing and comment them out. Kindly approve if everything is all good for your component if the UG looks good for you. This will likely go through another update before we properly push out v1.3.

Thanks guys. 👍

### CODE REVIEW

**Comment by SQwQ** [comment]
> addVisit, deleteVisit and editVisit are non-case sensitive now. I think inside the UG, we can just put it as "addvisit", "deletevisit" and "editvisit". What do you think?

+1

**Comment by Q-gabe** [comment]
@gachia @SQwQ Revised it to reflect lower case as suggested, I think it's a good point too. I also included this line under *Command Format* at Line 51. 👍 
`* All commands listed are *case-insensitive*.`

**Comment by ReignOfComputer** [comment]
LGTM, thanks Gabe. I have to add some stuff but will do it in a separate commit.

**Comment by SQwQ** [comment]
LGTM

**Pull request merged**
